sass:
  sass_dir: _sass
  style: :nested

excerpt_separator: <!--more-->

baseurl: /blog

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "smart"]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
