sass:
  sass_dir: _sass
  style: :nested

excerpt_separator: <!--more-->

# override with --baseurl "" when testing locally
baseurl: 

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  -
    scope:
      path: ""
      type: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
